version: "3"
services:
  powerdns:
    build: .
    container_name: powerdns
    image: trurlmcbyte/powerdns
    env_file:
      - .env
#    environment:
#      - PGSQL_HOST=${PGSQL_HOST}
#      - PGSQL_PORT=${PGSQL_PORT}
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
      - "8051:8051/tcp"

# docker run -v ./ex:/ex halkeye/powerdns zone2sql --zone=/ex/voletcard.com --gpgsql
