#!/bin/bash

set -e

if [ -n "$DEBUG_STARTUP" ]; then
	set -x
fi

printenv | grep PDNSSC_ | yq  -pp \
        '. | with_entries(.key |= (sub("^PDNSSC_","") | sub("_PLUS$","+") | downcase | sub("[._]","-"))) | .. | select(tag != "!!map" and tag != "!!seq") | ( (path | join("-")) + "=" + .)' \
         > /etc/powerdns/pdns.conf

# --help, --version
[ "$1" = "--help" ] || [ "$1" = "--version" ] && exec pdns_server $1
# treat everything except -- as exec cmd
[ "${1:0:2}" != "--" ] && exec "$@"

unset -v PGSQL_PASSWORD

trap "pdns_control quit" SIGINT SIGTERM
trap ":" SIGHUP
trap "set -x; pdns_control set query-logging yes" USR1
trap "set +x; pdns_control set query-logging no" USR2

pdns_server "$@" &
PID=$!

while true; do
	wait || true

	if ! kill -0 "$PID" >/dev/null 2>&1; then
		echo "PowerDNS has terminated, exiting" >&2
		exit 1
	fi
done

echo "CAN'T HAPPEN: DROPPED OUT OF INFINITE LOOP" >&2
exit 42

#yq '. *= load("conf.yaml") | ..  | select(tag != "!!map" and tag != "!!seq") | ( (path | join("-")) + "=" + .)' base.yaml
